#!/usr/local/bin/ruby -w

require 'pp'

class PP
  module PPMethods
    alias old_pp_hash pp_hash
    def pp_hash(obj)
      group(1, '{', '}') {
        seplist(obj, nil, :each_pair) {|k, v|
          group {
            pp k
            text ' => '
            group(1) {
              breakable ''
              pp v
            }
          }
        }
      }
    end
  end
end

# KLASSES[klass] = c_name
KLASSES = {}

# METHODS[klass][ruby_name] = c_name
METHODS = Hash.new { |h,k| h[k] = {} }

Dir.chdir ARGV.shift do
  Dir['*.c'].each do |c_file|
    File.open c_file do |fp|
      fp.each_line do |line|
        case line
        when /([^ ]+)\s+=\srb_define_class\("([^"]+)"/ then
          KLASSES[$1] = $2
        when /rb_define_method\(([^,]+),\s+"([^"]+)",\s+([^,]+), (-?\d+)/ then
          klass = KLASSES[$1]
          METHODS[klass][$2.intern] = $3, $4.to_i
        end
      end
    end
  end
end

print "RUBY_C_METHOD_MAP = "
pp METHODS

